### ISSUE TITLE
/menu broken

### ISSUE THREAD

**Issue by simplylate** [arcadiadevs/playerservers-everything#12]
On use of /menu and clicking on options it fires back an error ""Could not pass event InventoryClickEvent""

**Comment by OpenSource03** [comment]
Hi, can you please share the whole error log?

**Comment by simplylate** [comment]
On attempting to set max player slots I'm receiving errors like this, same with trying to set the MOTD.
`[09:42:21] [Server thread/ERROR]: Could not pass event InventoryClickEvent to PSServerCore v3.1
java.lang.ExceptionInInitializerError: null
	at xyz.tozymc.spigot.api.title.TitleApi.<init>(TitleApi.java:36) ~[PlayerServerCore.jar:?]
	at xyz.tozymc.spigot.api.title.TitleApi.<init>(TitleApi.java:30) ~[PlayerServerCore.jar:?]
	at xyz.tozymc.spigot.api.title.TitleApi$TitleApiHelper.<clinit>(TitleApi.java:121) ~[PlayerServerCore.jar:?]
	at xyz.tozymc.spigot.api.title.TitleApi.getInstance(TitleApi.java:46) ~[PlayerServerCore.jar:?]
	at xyz.tozymc.spigot.api.title.TitleApi.sendTitle(TitleApi.java:63) ~[PlayerServerCore.jar:?]
	at os.arcadiadevs.playerservers.servercore.listeners.MaxPlayersListener$1.getPromptText(MaxPlayersListener.java:76) ~[PlayerServerCore.jar:?]
	at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:290) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.conversations.ConversationTracker.beginConversation(ConversationTracker.java:21) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.beginConversation(CraftPlayer.java:2012) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.conversations.Conversation.begin(Conversation.java:191) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at os.arcadiadevs.playerservers.servercore.listeners.MaxPlayersListener.onClick(MaxPlayersListener.java:91) ~[PlayerServerCore.jar:?]
	at com.samjakob.spigui.menu.SGMenuListener.onInventoryClick(SGMenuListener.java:78) ~[PlayerServerCore.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-307]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3307) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant xyz.tozymc.minecraft.MinecraftVersion.v1_19_R1
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at xyz.tozymc.minecraft.MinecraftVersion.valueOf(MinecraftVersion.java:13) ~[PlayerServerCore.jar:?]
	at xyz.tozymc.minecraft.MinecraftVersion.<clinit>(MinecraftVersion.java:60) ~[PlayerServerCore.jar:?]
	... 34 more`

**Comment by OpenSource03** [comment]
This has been resolved. To fix it, remove PSServerCore from your Bungee/plugins/PlayerServers/templates folder and restart bungee. You have to do so manually as there is a bug in the current PS which stops it from replacing current ServerCore automatically.

 ServerCore will be updated on each subserver as soon as you restart it.
