### ISSUE TITLE
Cannot join other player's PS via hubcore compass

### ISSUE THREAD

**Issue by megatron0001** [arcadiadevs/playerservers-everything#16]
There is a bug in hubcore were you cannot join any other playerserver by using the compass in hubcore unless you try to join your own server

How to do:
1. Use latest playerserver and hubcore
2. Get an alt account or a friend to make a playerserver
3. Try to join it and it will not do anything if you try to join the playerserver by the hubcore compass (Server Selector)

**Comment by OpenSource03** [comment]
Does it work for you from "My PlayerServers" menu?

**Comment by megatron0001** [comment]
It does work with the emerald but not the server selector and now if you look on the other bug report I opened it has now just stopped

**Comment by Marko675** [comment]
The Emerald issue has been fixed, and it's working properly now. Make sure to use the latest config file from  https://github.com/arcadiadevs/hubcore/blob/3.1/src/main/resources/config.yml

You can download the latest HubCore from https://github.com/arcadiadevs/hubcore/actions/runs/4109103523

**Comment by megatron0001** [comment]
The emerald wasnt the issue it was the compass...

**Comment by Marko675** [comment]
Sorry, i meant with the compass :)

**Comment by megatron0001** [comment]
I still cannot open the compass up

**Comment by megatron0001** [comment]
It says

[00:55:07 ERROR]: Could not pass event PlayerInteractEvent to PSHubCore v3-dev
java.lang.NullPointerException: Cannot invoke "String.length()" because "replacement" is null
        at java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1014) ~[?:?]
        at java.util.regex.Matcher.appendReplacement(Matcher.java:997) ~[?:?]
        at java.util.regex.Matcher.replaceAll(Matcher.java:1181) ~[?:?]
        at java.lang.String.replaceAll(String.java:2950) ~[?:?]
        at os.arcadiadevs.playerservers.hubcore.guis.SelectorGui.lambda$openGui$7(SelectorGui.java:54) ~[PSHubCore.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:693) ~[?:?]
        at os.arcadiadevs.playerservers.hubcore.guis.SelectorGui.lambda$openGui$10(SelectorGui.java:56) ~[PSHubCore.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at os.arcadiadevs.playerservers.hubcore.guis.SelectorGui.openGui(SelectorGui.java:37) ~[PSHubCore.jar:?]
        at os.arcadiadevs.playerservers.hubcore.events.ClickEvent.onClick(ClickEvent.java:46) ~[PSHubCore.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-386]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546) ~[paper-1.19.3.jar:git-Paper-386]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[paper-1.19.3.jar:git-Paper-386]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[paper-1.19.3.jar:git-Paper-386]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:493) ~[paper-1.19.3.jar:git-Paper-386]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:489) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2017) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-386]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Comment by OpenSource03** [comment]
Please update your HubCore with this release:
https://github.com/arcadiadevs/hubcore/actions/runs/4109103523

Additionally, wait for PlayerServers Beta 4 on our Discord which will fix this issue.

If it happens afterwards, feel free to report it. Beta 4 will be released in a few hours most likely.

**Comment by megatron0001** [comment]
I did try that and everything works but just not the compass 🤔

**Comment by megatron0001** [comment]
But I can say PS3 is WAYY more stable and better than PS2 so its not much of an issue _but the crashing OOM killer is_

**Comment by OpenSource03** [comment]
> I did try that and everything works but just not the compass 🤔

Of course. Just wait for Beta 4 of the main plugin which will resolve it.

**Comment by megatron0001** [comment]
👍
