### ISSUE TITLE
[SEVERE] Cannot do anything

### ISSUE THREAD

**Issue by megatron0001** [arcadiadevs/playerservers-everything#18]
[qtp1525185448-29] WARN org.eclipse.jetty.server.HttpChannel - /api/servers/Jhb_/actions/remove
java.lang.ClassFormatError: Duplicate method name "run" with signature "(I)Lxyz.arcadiadevs.playerservers.daemon.docker.StopContainer;" in class file xyz/arcadiadevs/playerservers/daemon/docker/StopContainer
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at xyz.arcadiadevs.playerservers.daemon.routes.serveractions.ServerRemover.runDockerAction(ServerRemover.java)
        at xyz.arcadiadevs.playerservers.daemon.routes.serveractions.ServerActions.handle(ServerActions.java)
        at spark.RouteImpl$1.handle(RouteImpl.java:72)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1598)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:1589)

This also applys to deleting, starting, creating and stopping

**Comment by megatron0001** [comment]
20:47:51 [SEVERE] Exception in thread "Thread-27"
20:47:51 [SEVERE] java.lang.IllegalArgumentException: Illegal group reference

20:47:51 [SEVERE]     at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1067)

20:47:51 [SEVERE]     at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:997)

20:47:51 [SEVERE]     at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1181)

20:47:51 [SEVERE]     at java.base/java.lang.String.replaceAll(String.java:2950)

20:47:51 [SEVERE]     at os.arcadiadevs.playerservers.serveractions.ServerStarter.sendToServer(ServerStarter.java)

20:47:51 [SEVERE]     at os.arcadiadevs.playerservers.serveractions.ServerActions.lambda$run$0(ServerActions.java)

20:47:51 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:1589)

20:48:01 [SEVERE] Exception in thread "Thread-28"
20:48:01 [SEVERE] java.lang.IllegalArgumentException: Illegal group reference

20:48:01 [SEVERE]     at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1067)

20:48:01 [SEVERE]     at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:997)

20:48:01 [SEVERE]     at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1181)

20:48:01 [SEVERE]     at java.base/java.lang.String.replaceAll(String.java:2950)

20:48:01 [SEVERE]     at os.arcadiadevs.playerservers.serveractions.ServerRemover.sendToServer(ServerRemover.java)

20:48:01 [SEVERE]     at os.arcadiadevs.playerservers.serveractions.ServerActions.lambda$run$0(ServerActions.java)

20:48:01 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:1589)

20:53:24 [SEVERE] Exception in thread "Thread-32"
20:53:24 [SEVERE] java.lang.IllegalArgumentException: Illegal group reference

20:53:24 [SEVERE]     at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1067)

20:53:24 [SEVERE]     at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:997)

20:53:24 [SEVERE]     at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1181)

20:53:24 [SEVERE]     at java.base/java.lang.String.replaceAll(String.java:2950)

20:53:24 [SEVERE]     at os.arcadiadevs.playerservers.serveractions.ServerKiller.sendToServer(ServerKiller.java)

20:53:24 [SEVERE]     at os.arcadiadevs.playerservers.serveractions.ServerActions.lambda$run$0(ServerActions.java)

20:53:24 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:1589)

20:53:25 [SEVERE] Exception in thread "Thread-33"
20:53:25 [SEVERE] java.lang.IndexOutOfBoundsException: No group 1

20:53:25 [SEVERE]     at java.base/java.util.regex.Matcher.start(Matcher.java:482)

20:53:25 [SEVERE]     at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1090)

20:53:25 [SEVERE]     at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:997)

20:53:25 [SEVERE]     at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1181)

20:53:25 [SEVERE]     at java.base/java.lang.String.replaceAll(String.java:2950)

20:53:25 [SEVERE]     at os.arcadiadevs.playerservers.serveractions.ServerKiller.sendToServer(ServerKiller.java)

20:53:25 [SEVERE]     at os.arcadiadevs.playerservers.serveractions.ServerActions.lambda$run$0(ServerActions.java)

20:53:25 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by OpenSource03** [comment]
This has been resolved, read
https://discord.com/channels/664882829527744542/1072605743238361190/1072657840717693048
