### ISSUE TITLE
Daemon screen error

### ISSUE THREAD

**Issue by Monty70** [arcadiadevs/playerservers-everything#2]
After downloading, extracting and uploading the PlayerServersDaemon.jar file (from https://playerservers.thearcadia.xyz/overview/installation/multi-node-support) to a newly reinstalled Debian 10 machine with JAVA 18 installed in the /root/Daemon folder and running the command "java -Xmx200M -jar Daemon.jar" I get this error:

```root@PlayerServer:~/Daemon# java -Xmx200M -jar Daemon.jar
[2022-09-28 00:09:35] [INFO   ] Starting PlayerServers Daemon
[2022-09-28 00:09:35] [WARNING] Logs file does not exist, creating a new one
[2022-09-28 00:09:35] [WARNING] Config does not exist, creating it now.
[2022-09-28 00:09:35] [INFO   ] Created servers folder
[2022-09-28 00:09:35] [INFO   ] Created templates folder
[2022-09-28 00:09:35] [WARNING] Created templates/plugins-to-be-added-ingame folder
[2022-09-28 00:09:35] [INFO   ] Created templates/default folder
Exception in thread "main" java.lang.VerifyError: Expecting a stack map frame
Exception Details:
  Location:
    xyz/arcadiadevs/playerservers/daemon/utils/FileUtils.<clinit>()V @179: iload_3
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 1011 bd01 24b3 0658 b206 5803 1306 5a53
    0000010: b206 5804 1306 5c53 b206 5805 1306 5e53
    0000020: b206 5806 1306 6053 b206 5807 1306 6253
    0000030: b206 5808 1306 6453 b206 5810 0613 0666
    0000040: 53b2 0658 1007 1306 6853 b206 5810 0813
    0000050: 066a 53b2 0658 1009 1306 6c53 b206 5810
    0000060: 0a13 066e 53b2 0658 100b 1306 7053 b206
    0000070: 5810 0c13 0672 53b2 0658 100d 1306 7453
    0000080: b206 5810 0e13 0676 53b2 0658 100f 1306
    0000090: 7853 b206 5810 1013 067a 5313 067b 1306
    00000a0: 7c13 067e b800 2382 823e 1306 7f1d 82b3
    00000b0: 04ed b11d 101f 6807 7c1d 701d 1010 7c82
    00000c0: 1306 80a0 00d5 1306 811d 823e 1d13 0682
    00000d0: 1d82 6813 0683 1d82 7c1d 701d 1306 841d
    00000e0: 827c 8213 0685 1d82 9f00 1801 bf1d 101f
    00000f0: 6807 7c1d 701d 1010 7c82 1306 86a0 001e
    0000100: bb00 2e59 b700 33bf 1d10 1f68 077c 1d70
    0000110: 1d10 107c 8213 0687 a000 76bb 002a 4e2d
    0000120: b700 392d bf1d 1007 101d 787e 101d 7a1d
    0000130: 0678 80ab 0000 0019 0000 0002 a4c4 a1b8
    0000140: 0000 0025 bd17 a232 0000 002e bb00 2e4e
    0000150: 2d12 3cb7 00a6 2dbf 1306 881d 823e a700
    0000160: 0913 0689 1d82 3e57 1d10 1f68 077c 1d70
    0000170: 1d10 107c 8213 068a a000 0c13 068b 1d82
    0000180: 3ea7 000d bb00 2a4e 2db7 0039 2dbf bb00
    0000190: 2c4e 2db7 0052 2dbf bb00 2a4e 2db7 0039
    00001a0: 2dbf
  Exception Handler Table:
    bci [204, 283] => handler: 293

        at xyz.arcadiadevs.playerservers.daemon.Core.<init>(Unknown Source)
        at xyz.arcadiadevs.playerservers.daemon.Daemon.<init>(Unknown Source)
        at xyz.arcadiadevs.playerservers.daemon.Launcher.main(Unknown Source)
```
The files are created.
I will create a start.sh file with the contents:

```screen -dmS Daemon java -Xmx200M -jar Daemon.jar```

I run ./start.sh. But the screen won't start

```
root@PlayerServer:~/Daemon# ./start.sh
root@PlayerServer:~/Daemon# screen -ls
No Sockets found in /run/screen/S-root.

root@PlayerServer:~/Daemon# screen -r Daemon
There is no screen to be resumed matching Daemon.
root@PlayerServer:~/Daemon#

```

**Comment by OpenSource03** [comment]
This issue should be fixed in v3.1
