### ISSUE TITLE
Pterodactyl install broken

### ISSUE THREAD

**Issue by megatron0001** [arcadiadevs/playerservers-everything#31]
When trying to create a new player server and when it tries to install on pterodactyl then start it, it will come up with this error:

container@pterodactyl~ java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.6+10) Host: Linux 5.15.0-1029-oracle (aarch64)
Loading libraries, please wait...
[22:35:09 INFO]: Building unoptimized datafixer
java.lang.ExceptionInInitializerError
        at io.papermc.paper.world.structure.PaperConfiguredStructure.init(PaperConfiguredStructure.java:26)
        at net.minecraft.world.level.levelgen.structure.Structure.<clinit>(Structure.java:45)
        at net.minecraft.world.level.levelgen.structure.StructureSet$a.a(StructureSet.java:32)
        at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72)
        at net.minecraft.world.level.levelgen.structure.StructureSet$a.<clinit>(StructureSet.java:32)
        at net.minecraft.world.level.levelgen.structure.StructureSet.a(StructureSet.java:14)
        at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72)
        at net.minecraft.world.level.levelgen.structure.StructureSet.<clinit>(StructureSet.java:14)
        at net.minecraft.world.level.levelgen.structure.placement.StructurePlacement$a.a(StructurePlacement.java:131)
        at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72)
        at net.minecraft.world.level.levelgen.structure.placement.StructurePlacement$a.<clinit>(StructurePlacement.java:130)
        at net.minecraft.world.level.levelgen.structure.placement.StructurePlacement.a(StructurePlacement.java:31)
        at net.minecraft.world.level.levelgen.structure.placement.RandomSpreadStructurePlacement.b(RandomSpreadStructurePlacement.java:15)
        at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
        at net.minecraft.world.level.levelgen.structure.placement.RandomSpreadStructurePlacement.<clinit>(RandomSpreadStructurePlacement.java:15)
        at net.minecraft.world.level.levelgen.structure.placement.StructurePlacementType.<clinit>(StructurePlacementType.java:14)
        at net.minecraft.core.registries.BuiltInRegistries.n(BuiltInRegistries.java:231)
        at net.minecraft.core.registries.BuiltInRegistries.a(BuiltInRegistries.java:306)
        at net.minecraft.core.registries.BuiltInRegistries.lambda$createContents$54(BuiltInRegistries.java:326)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at net.minecraft.core.registries.BuiltInRegistries.b(BuiltInRegistries.java:325)
        at net.minecraft.core.registries.BuiltInRegistries.bootStrap(BuiltInRegistries.java:318)
        at net.minecraft.server.DispenserRegistry.a(DispenserRegistry.java:73)
        at net.minecraft.server.Main.main(Main.java:114)
        at org.bukkit.craftbukkit.Main.main(Main.java:302)
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.Server.getRegistry(java.lang.Class)" because "org.bukkit.Bukkit.server" is null
        at org.bukkit.Bukkit.getRegistry(Bukkit.java:2272)
        at org.bukkit.Registry.<clinit>(Registry.java:139)
        ... 27 more

**Comment by OpenSource03** [comment]
This looks to be a Pterodactyl issue.

Please try with a different version in config.yml under Pterodactyl environment variables. Default is 1.8 and it may not be supported by your system for some reason.

**Comment by NoahvdAa** [comment]
This was caused by a broken Paper commit, should be fixed in build 402 :)
