### ISSUE TITLE
PlayerServers-v3-beta2.jar - error in console

### ISSUE THREAD

**Issue by Monty70** [arcadiadevs/playerservers-everything#4]
On startup there is this error in the console:

```
20:27:58 [INFO] PlayerServers - Starting...
20:27:58 [INFO] PlayerServers - Added connection com.mysql.cj.jdbc.ConnectionImpl@5eaa4ed0
20:27:58 [INFO] PlayerServers - Start completed.
20:27:58 [SEVERE] java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN SERVERID TO ServerID' at line 1
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
20:27:58 [SEVERE]     at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
20:27:58 [SEVERE]     at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
20:27:58 [SEVERE]     at os.arcadiadevs.playerservers.data.migrations.RenameVariables.migrate(Unknown Source)
20:27:58 [SEVERE]     at os.arcadiadevs.playerservers.data.DataBase.executeMigrations(Unknown Source)
20:27:58 [SEVERE]     at os.arcadiadevs.playerservers.data.DataBase.checkForUpdates(Unknown Source)
20:27:58 [SEVERE]     at os.arcadiadevs.playerservers.PlayerServers.onEnable(Unknown Source)
20:27:58 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
20:27:58 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
20:27:58 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
20:27:58 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
20:27:58 [SEVERE] java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN PORT TO Port' at line 1
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
20:27:58 [SEVERE]     at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
20:27:58 [SEVERE]     at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
20:27:58 [SEVERE]     at os.arcadiadevs.playerservers.data.migrations.RenameVariables.migrate(Unknown Source)
20:27:58 [SEVERE]     at os.arcadiadevs.playerservers.data.DataBase.executeMigrations(Unknown Source)
20:27:58 [SEVERE]     at os.arcadiadevs.playerservers.data.DataBase.checkForUpdates(Unknown Source)
20:27:58 [SEVERE]     at os.arcadiadevs.playerservers.PlayerServers.onEnable(Unknown Source)
20:27:58 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
20:27:58 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
20:27:58 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
20:27:58 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
20:27:58 [SEVERE] java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN PLAYERNAME TO PlayerName' at line 1
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
20:27:58 [SEVERE]     at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
20:27:58 [SEVERE]     at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
20:27:58 [SEVERE]     at os.arcadiadevs.playerservers.data.migrations.RenameVariables.migrate(Unknown Source)
20:27:58 [SEVERE]     at os.arcadiadevs.playerservers.data.DataBase.executeMigrations(Unknown Source)
20:27:58 [SEVERE]     at os.arcadiadevs.playerservers.data.DataBase.checkForUpdates(Unknown Source)
20:27:58 [SEVERE]     at os.arcadiadevs.playerservers.PlayerServers.onEnable(Unknown Source)
20:27:58 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
20:27:58 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
20:27:58 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
20:27:58 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
20:27:58 [SEVERE] java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN NODE TO Node' at line 1
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
20:27:58 [SEVERE]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
20:27:58 [SEVERE]     at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
20:27:58 [SEVERE]     at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
20:27:58 [SEVERE]     at os.arcadiadevs.playerservers.data.migrations.RenameVariables.migrate(Unknown Source)
20:27:58 [SEVERE]     at os.arcadiadevs.playerservers.data.DataBase.executeMigrations(Unknown Source)
20:27:58 [SEVERE]     at os.arcadiadevs.playerservers.data.DataBase.checkForUpdates(Unknown Source)
20:27:58 [SEVERE]     at os.arcadiadevs.playerservers.PlayerServers.onEnable(Unknown Source)
20:27:58 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
20:27:58 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
20:27:58 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
20:27:58 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
20:27:58 [INFO] Enabled plugin PlayerServers version v3-dev by OpenSource
```
bungeecord 1.19.2

Screen database table:

https://i.imgur.com/SQmuCEl.png

https://i.imgur.com/XG1mvam.png

both tables are still empty, Daemon for NODE is not working, so I haven't created any sevrer yet.

**Comment by OpenSource03** [comment]
Fixed in 3.1, releasing January the 1st.
