### ISSUE TITLE
psadmin command does not function on bungeecord

### ISSUE THREAD

**Issue by megatron0001** [arcadiadevs/playerservers-everything#48]
If you execute the command "psadmin" on the bungeecord proxy, It should work or should block the command instead it puts this command in the console

[19:02:29 INFO]: An internal error occurred whilst executing this command, please check the console log for details.
[19:02:29 WARN]: Error in dispatching command
java.lang.ClassCastException: class net.md_5.bungee.command.ConsoleCommandSender cannot be cast to class net.md_5.bungee.api.connection.ProxiedPlayer (net.md_5.bungee.command.ConsoleCommandSender and net.md_5.bungee.api.connection.ProxiedPlayer are in unnamed module of loader 'app')
        at os.arcadiadevs.playerservers.commands.AdminCommands.execute(AdminCommands.java) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:213) ~[proxy-525.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f344c08:525]
        at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:164) ~[proxy-525.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f344c08:525]
        at io.github.waterfallmc.waterfall.console.WaterfallConsole.runCommand(WaterfallConsole.java:30) ~[proxy-525.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f344c08:525]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:87) ~[proxy-525.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f344c08:525]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:168) ~[proxy-525.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f344c08:525]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) ~[proxy-525.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f344c08:525]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:72) ~[proxy-525.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f344c08:525]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[proxy-525.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f344c08:525]

**Comment by Marko675** [comment]
This issue will be fixed in the latest build (soon we will upload it)
