### ISSUE TITLE
Subdomains do not function

### ISSUE THREAD

**Issue by megatron0001** [arcadiadevs/playerservers-everything#52]
[17:49:02 ERROR]: java.io.IOException: Unexpected code Response{protocol=h2, code=404, message=, url=https://api.cloudflare.com/client/v4/zones//dns_records} {"result":null,"success":false,"errors":[{"code":7003,"message":"Could not route to /client/v4/zones/dns_records, perhaps your object identifier is invalid?"}],"messages":[]}
[17:49:02 ERROR]:       at os.arcadiadevs.playerservers.cloudflare.CloudflareRequest.lambda$getAsync$0(:70)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[17:49:02 ERROR]: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: Unexpected code Response{protocol=h2, code=404, message=, url=https://api.cloudflare.com/client/v4/zones//dns_records} {"result":null,"success":false,"errors":[{"code":7003,"message":"Could not route to /client/v4/zones/dns_records, perhaps your object identifier is invalid?"}],"messages":[]}
[17:49:02 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[17:49:02 ERROR]:       at os.arcadiadevs.playerservers.services.CloudflareService.getIfExists(:124)
[17:49:02 ERROR]:       at os.arcadiadevs.playerservers.services.CloudflareService.createDomain(:44)
[17:49:02 ERROR]:       at os.arcadiadevs.playerservers.serveractions.ServerCreator.lambda$runPanelAction$4(:284)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[17:49:02 ERROR]: Caused by: java.lang.RuntimeException: java.io.IOException: Unexpected code Response{protocol=h2, code=404, message=, url=https://api.cloudflare.com/client/v4/zones//dns_records} {"result":null,"success":false,"errors":[{"code":7003,"message":"Could not route to /client/v4/zones/dns_records, perhaps your object identifier is invalid?"}],"messages":[]}
[17:49:02 ERROR]:       at os.arcadiadevs.playerservers.cloudflare.CloudflareRequest.lambda$getAsync$0(:77)
[17:49:02 ERROR]:       ... 7 more
[17:49:02 ERROR]: Caused by: java.io.IOException: Unexpected code Response{protocol=h2, code=404, message=, url=https://api.cloudflare.com/client/v4/zones//dns_records} {"result":null,"success":false,"errors":[{"code":7003,"message":"Could not route to /client/v4/zones/dns_records, perhaps your object identifier is invalid?"}],"messages":[]}
[17:49:02 ERROR]:       at os.arcadiadevs.playerservers.cloudflare.CloudflareRequest.lambda$getAsync$0(:70)
[17:49:02 ERROR]:       ... 7 more
[17:49:02 ERROR]: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: Unexpected code Response{protocol=h2, code=404, message=, url=https://api.cloudflare.com/client/v4/zones//dns_records} {"result":null,"success":false,"errors":[{"code":7003,"message":"Could not route to /client/v4/zones/dns_records, perhaps your object identifier is invalid?"}],"messages":[]}
[17:49:02 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[17:49:02 ERROR]: Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: Unexpected code Response{protocol=h2, code=404, message=, url=https://api.cloudflare.com/client/v4/zones//dns_records} {"result":null,"success":false,"errors":[{"code":7003,"message":"Could not route to /client/v4/zones/dns_records, perhaps your object identifier is invalid?"}],"messages":[]}
[17:49:02 ERROR]:       at os.arcadiadevs.playerservers.services.CloudflareService.getIfExists(:127)
[17:49:02 ERROR]:       at os.arcadiadevs.playerservers.services.CloudflareService.createDomain(:44)
[17:49:02 ERROR]:       at os.arcadiadevs.playerservers.serveractions.ServerCreator.lambda$runPanelAction$4(:284)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[17:49:02 ERROR]:       ... 6 more
[17:49:02 ERROR]: Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: Unexpected code Response{protocol=h2, code=404, message=, url=https://api.cloudflare.com/client/v4/zones//dns_records} {"result":null,"success":false,"errors":[{"code":7003,"message":"Could not route to /client/v4/zones/dns_records, perhaps your object identifier is invalid?"}],"messages":[]}
[17:49:02 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[17:49:02 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[17:49:02 ERROR]:       at os.arcadiadevs.playerservers.services.CloudflareService.getIfExists(:124)
[17:49:02 ERROR]:       ... 9 more
[17:49:02 ERROR]: Caused by: java.lang.RuntimeException: java.io.IOException: Unexpected code Response{protocol=h2, code=404, message=, url=https://api.cloudflare.com/client/v4/zones//dns_records} {"result":null,"success":false,"errors":[{"code":7003,"message":"Could not route to /client/v4/zones/dns_records, perhaps your object identifier is invalid?"}],"messages":[]}
[17:49:02 ERROR]:       at os.arcadiadevs.playerservers.cloudflare.CloudflareRequest.lambda$getAsync$0(:77)
[17:49:02 ERROR]:       ... 7 more
[17:49:02 ERROR]: Caused by: java.io.IOException: Unexpected code Response{protocol=h2, code=404, message=, url=https://api.cloudflare.com/client/v4/zones//dns_records} {"result":null,"success":false,"errors":[{"code":7003,"message":"Could not route to /client/v4/zones/dns_records, perhaps your object identifier is invalid?"}],"messages":[]}
[17:49:02 ERROR]:       at os.arcadiadevs.playerservers.cloudflare.CloudflareRequest.lambda$getAsync$0(:70)
[17:49:02 ERROR]:       ... 7 more
<img width="321" alt="image" src="https://github.com/arcadiadevs/playerservers-everything/assets/82678869/9e25d624-2004-492d-b76c-5b93d513015b">

When a player attempts to try to create a server it fails due to this error above.

**Comment by expxx** [comment]
That's just your token being invalid? Not a bug..

**Comment by OpenSource03** [comment]
That's you not updating the config :P I bet you don't have the config for your zone ID in your config.

**Comment by megatron0001** [comment]
> That's just your token being invalid? Not a bug..

Have you even tested the cloudflare subdomain option?

**Comment by OpenSource03** [comment]
Hi @Hexatronic01, the issue was caused by wrong config.

Rename zone_id to zone-id in config and it will work.
