### ISSUE TITLE
Subdomain error

### ISSUE THREAD

**Issue by cinortaxeh** [arcadiadevs/playerservers-everything#54]
[23:34:37 ERROR]: java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
[23:34:37 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[23:34:37 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[23:34:37 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[23:34:37 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[23:34:37 ERROR]:       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[23:34:37 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
[23:34:37 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)
[23:34:37 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
[23:34:37 ERROR]:       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[23:34:37 ERROR]: Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
[23:34:37 ERROR]:       at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
[23:34:37 ERROR]:       at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[23:34:37 ERROR]:       at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[23:34:37 ERROR]:       at java.base/java.util.Objects.checkIndex(Objects.java:385)
[23:34:37 ERROR]:       at java.base/java.util.ArrayList.get(ArrayList.java:427)
[23:34:37 ERROR]:       at os.arcadiadevs.playerservers.services.CloudflareService.getIfExists(:140)
[23:34:37 ERROR]:       at os.arcadiadevs.playerservers.services.CloudflareService.createDomain(:44)
[23:34:37 ERROR]:       at os.arcadiadevs.playerservers.serveractions.ServerCreator.lambda$runPanelAction$4(:286)
[23:34:37 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[23:34:37 ERROR]:       ... 6 more

Why do things not work...

**Comment by OpenSource03** [comment]
We will review your request during the next week. Meanwhile, please open up a ticket on our Discord so we can learn more about this issue and help you further.
