### ISSUE TITLE
Server creation issue

### ISSUE THREAD

**Issue by megatron0001** [arcadiadevs/playerservers-everything#55]
[18:55:29 ERROR]: com.mattmalec.pterodactyl4j.exceptions.HttpException: Pterodactyl4J has encountered a 400 error.
[18:55:29 ERROR]:
[18:55:29 ERROR]:       - No nodes satisfying the requirements specified for automatic deployment could be found.
[18:55:29 ERROR]:
[18:55:29 ERROR]:       at com.mattmalec.pterodactyl4j.requests.PteroActionImpl.execute(PteroActionImpl.java:99)
[18:55:29 ERROR]:       at com.mattmalec.pterodactyl4j.PteroAction.execute(PteroAction.java:97)
[18:55:29 ERROR]:       at os.arcadiadevs.playerservers.serveractions.ServerCreator.lambda$runPanelAction$4(:245)
[18:55:29 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[18:55:29 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[18:55:29 ERROR]:       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[18:55:29 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
[18:55:29 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)
[18:55:29 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
[18:55:29 ERROR]:       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

Fix...

**Comment by OpenSource03** [comment]
This issue is descriptive and coming from Pterodactyl. Make sure you have a node with enough resources.
