### ISSUE TITLE
Daemon screen error #2

### ISSUE THREAD

**Issue by Monty70** [arcadiadevs/playerservers-everything#6]
Thanks for the PlayerServersDaemon.jar update, however the situation is the same, just with a different error.

After downloading, extracting and uploading the PlayerServersDaemon.jar file (from https://playerservers.thearcadia.xyz/overview/installation/multi-node-support) to a newly reinstalled Debian 10 machine with JAVA 18 installed in the /root/Daemon folder and running the command "java -Xmx200M -jar Daemon.jar" I get this error:
```
root@instance-20220916-0526:~# cd /root/Daemon/
root@instance-20220916-0526:~/Daemon# java -Xmx200M -jar Daemon.jar
[2022-10-02 19:27:08] [INFO   ] Starting PlayerServers Daemon
[2022-10-02 19:27:08] [WARNING] Logs file does not exist, creating a new one
[2022-10-02 19:27:08] [WARNING] Config does not exist, creating it now.
[2022-10-02 19:27:08] [INFO   ] Created servers folder
[2022-10-02 19:27:08] [INFO   ] Created templates folder
[2022-10-02 19:27:08] [WARNING] Created templates/plugins-to-be-added-ingame folder
[2022-10-02 19:27:08] [INFO   ] Created templates/default folder
Exception in thread "main" java.lang.VerifyError: Instruction type does not match stack map
Exception Details:
  Location:
    xyz/arcadiadevs/playerservers/daemon/utils/FileUtils.thisIsAInsaneEncryptionMethod(Ljava/lang/String;I)Ljava/lang/String; @933: aload
  Reason:
    Type 'java/util/Base64$Decoder' (current frame, locals[2]) is not assignable to '[B' (stack map, locals[2])
  Current Frame:
    bci: @933
    flags: { }
    locals: { 'java/lang/String', integer, 'java/util/Base64$Decoder', integer, integer, '[B', 'java/lang/String', '[B', integer, '[B', integer, top, '[B', top, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, top, top, top, top, top, top, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer }
    stack: { }
  Stackmap Frame:
    bci: @933
    flags: { }
    locals: { 'java/lang/String', integer, '[B', '[B', '[B', integer }
    stack: { }
  Bytecode:
    0000000: b806 914d 2ab6 0695 3a0c 2c19 0cb6 069b
    0000010: 3a05 1bb8 069d 3a06 1906 b606 953a 0710
    0000020: 3c36 0815 08bc 083a 0903 3e10 4836 0419
    0000030: 091d 1504 5404 360e 1043 364f 1909 150e
    0000040: 154f 5405 360f 0836 5019 0915 0f15 5054
    0000050: 0636 1010 6236 5119 0915 1015 5154 0736
    0000060: 1110 1b36 5219 0915 1115 5254 0836 1210
    0000070: 3036 5319 0915 1215 5354 1006 3613 106b
    0000080: 3654 1909 1513 1554 5410 0736 1410 3c36
    0000090: 5519 0915 1415 5554 1008 3615 106b 3656
    00000a0: 1909 1515 1556 5410 0936 1610 3436 5719
    00000b0: 0915 1615 5754 100a 3617 1021 3658 1909
    00000c0: 1517 1558 5410 0b36 1810 3236 5919 0915
    00000d0: 1815 5954 100c 3619 105a 365a 1909 1519
    00000e0: 155a 5410 0d36 1a10 6636 5b19 0915 1a15
    00000f0: 5b54 100e 361b 1062 365c 1909 151b 155c
    0000100: 5410 0f36 1c10 3236 5d19 0915 1c15 5d54
    0000110: 1010 361d 106c 365e 1909 151d 155e 5410
    0000120: 1136 1e10 0636 5f19 0915 1e15 5f54 1012
    0000130: 361f 1026 3660 1909 151f 1560 5410 1336
    0000140: 2010 2e36 6119 0915 2015 6154 1014 3621
    0000150: 1066 3662 1909 1521 1562 5410 1536 2210
    0000160: 4336 6319 0915 2215 6354 1016 3623 107c
    0000170: 3664 1909 1523 1564 5410 1736 2410 7136
    0000180: 6519 0915 2415 6554 1018 3625 101d 3666
    0000190: 1909 1525 1566 5410 1936 2610 4936 6719
    00001a0: 0915 2615 6754 101a 3627 1036 3668 1909
    00001b0: 1527 1568 5410 1b36 2810 2a36 6919 0915
    00001c0: 2815 6954 101c 3629 1062 366a 1909 1529
    00001d0: 156a 5410 1d36 2a10 1436 6b19 0915 2a15
    00001e0: 6b54 101e 362b 105a 366c 1909 152b 156c
    00001f0: 5410 1f36 2c10 4b36 6d19 0915 2c15 6d54
    0000200: 1020 362d 104f 366e 1909 152d 156e 5410
    0000210: 2136 2e10 0b36 6f19 0915 2e15 6f54 1022
    0000220: 362f 101f 3670 1909 152f 1570 5410 2336
    0000230: 3010 2336 7119 0915 3015 7154 1024 3631
    0000240: 1006 3672 1909 1531 1572 5410 2536 3210
    0000250: 6c36 7319 0915 3215 7354 1026 3633 1050
    0000260: 3674 1909 1533 1574 5410 2736 3410 4536
    0000270: 7519 0915 3415 7554 1028 3635 1015 3676
    0000280: 1909 1535 1576 5410 2936 3610 2b36 7719
    0000290: 0915 3615 7754 102a 3637 0636 7819 0915
    00002a0: 3715 7854 102b 3638 1008 3679 1909 1538
    00002b0: 1579 5410 2c36 3910 6b36 7a19 0915 3915
    00002c0: 7a54 102d 363a 1066 367b 1909 153a 157b
    00002d0: 5410 2e36 3b10 5a36 7c19 0915 3b15 7c54
    00002e0: 102f 363c 102a 367d 1909 153c 157d 5410
    00002f0: 3036 3d05 367e 1909 153d 157e 5410 3136
    0000300: 3e10 3136 7f19 0915 3e15 7f54 1032 363f
    0000310: 1017 3680 1909 153f 1580 5410 3336 4010
    0000320: 6e36 8119 0915 4015 8154 1034 3641 107d
    0000330: 3682 1909 1541 1582 5410 3536 4210 0b36
    0000340: 8319 0915 4215 8354 1036 3643 1030 3684
    0000350: 1909 1543 1584 5410 3736 4410 7b36 8519
    0000360: 0915 4415 8554 1038 3645 103c 3686 1909
    0000370: 1545 1586 5410 3936 4610 7f36 8719 0915
    0000380: 4615 8754 103a 3647 1014 3688 1909 1547
    0000390: 1588 5410 3b36 4810 0936 8919 0915 4815
    00003a0: 8954 0336 0a19 05be 360d 150a 150d a200
    00003b0: 6619 0515 0a33 3649 1907 be36 8e15 0a15
    00003c0: 8e70 368c 1907 158c 3336 8a15 4915 8a82
    00003d0: 364a 154a 9136 4b19 0515 0a15 4b54 1905
    00003e0: 150a 3336 4c19 09be 368f 150a 158f 7036
    00003f0: 8d19 0915 8d33 368b 154c 158b 8236 4d15
    0000400: 4d91 364e 1905 150a 154e 5415 0a04 6036
    0000410: 0aa7 ff94 bb01 243a 0b19 0b19 05b7 06a2
    0000420: 190b b0
  Stackmap Table:
    full_frame(@933,{Object[#292],Integer,Object[#1695],Object[#1695],Object[#1695],Integer},{})
    chop_frame(@1044,1)

        at xyz.arcadiadevs.playerservers.daemon.Core.<init>(Unknown Source)
        at xyz.arcadiadevs.playerservers.daemon.Daemon.<init>(Unknown Source)
        at xyz.arcadiadevs.playerservers.daemon.Launcher.main(Unknown Source)
root@instance-20220916-0526:~/Daemon# ./start.sh
```

The files are created.
I will create a start.sh file with the contents:

screen -dmS Daemon java -Xmx200M -jar Daemon.jar

I run ./start.sh. But the screen won't start

**Comment by OpenSource03** [comment]
Should be fixed in the upcoming Daemon - "Dragon", coming between 1st and 3rd of January.
